spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/auth_test?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create